[SERVICE]
    Flush           1
    Daemon          Off
    Log_Level       info
    Parsers_File    /fluent-bit/etc/parsers.conf

[INPUT]
    Name            tail
    Path            /var/log/hayabusa-host/linux-*.log
    Tag             host.logs
    Read_from_Head  true
    Refresh_Interval 2
    DB              /tmp/flb_tail.db
    Mem_Buf_Limit   5MB

[INPUT]
    Name            tail
    Path            /var/log/hayabusa-host/windows-events.log
    Tag             windows.events
    Read_from_Head  true
    Refresh_Interval 2
    DB              /tmp/flb_tail_windows.db
    Mem_Buf_Limit   5MB

[FILTER]
    Name            parser
    Match           windows.events
    Key_Name        log
    Parser          json
    Reserve_Data    On

[FILTER]
    Name            record_modifier
    Match           host.logs
    Record          collector fluent-bit
    Record          host_collection linux-file-tail

[FILTER]
    Name            record_modifier
    Match           windows.events
    Record          collector fluent-bit-windows
    Record          host_collection windows-eventlog-sim

[OUTPUT]
    Name            forward
    Match           host.logs
    Host            vector
    Port            24224
    Retry_Limit     False

[OUTPUT]
    Name            forward
    Match           windows.events
    Host            vector
    Port            24225
    Retry_Limit     False
    tls             On
    tls.verify      On
    tls.ca_file     /etc/fluent-bit/tls/windows-forward/ca.crt
    tls.crt_file    /etc/fluent-bit/tls/windows-forward/client.crt
    tls.key_file    /etc/fluent-bit/tls/windows-forward/client.key
