-- Hayabusa events table
-- Runs once on first ClickHouse container startup via /docker-entrypoint-initdb.d/
--
-- Schema uses a small set of stable anchor columns present in every event,
-- plus a Map(String, String) for all variable source fields. This avoids
-- schema migrations when the ingest source format changes.
--
-- TTL: 7 days (local synthetic-traffic default).
-- To adjust: ALTER TABLE security.events MODIFY TTL ts + INTERVAL N DAY;
-- To remove: ALTER TABLE security.events REMOVE TTL;

CREATE TABLE IF NOT EXISTS security.events
(
    ts            DateTime64(3, 'UTC'),           -- event timestamp (millisecond precision)
    event_id      UUID DEFAULT generateUUIDv4(),  -- deduplication key, generated by ClickHouse
    platform      LowCardinality(String),         -- deployment tag, e.g. "local-mvp"
    ingest_source LowCardinality(String),         -- collector that produced the event
    message       String,                         -- normalized human-readable message
    fields        Map(String, String)             -- all other source-specific fields
)
ENGINE = MergeTree()
PARTITION BY toYYYYMM(ts)
ORDER BY (ts, platform)
TTL ts + INTERVAL 7 DAY;
